"""
Build v1.4 from v1.3: preserves all 71 existing sheets, appends the C-004D
thermodynamic generator reconciliation sheets.
"""
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter
import json

SRC = "/home/user/URSP/workbook/Universal_Rosetta_Stone_MASTER_CALCULATION_WORKBOOK_v1.3.xlsx"
OUT = "/home/user/URSP/workbook/Universal_Rosetta_Stone_MASTER_CALCULATION_WORKBOOK_v1.4.xlsx"
RECON = "/home/user/URSP/reconstruction"

with open(f"{RECON}/c004d_generator_results.json") as f:
    G = json.load(f)

wb = openpyxl.load_workbook(SRC, data_only=False)

TITLE_FONT = Font(name="Arial", size=12, bold=True)
HEADER_FONT = Font(name="Arial", size=10, bold=True, color="FFFFFF")
HEADER_FILL = PatternFill("solid", fgColor="4472C4")
BODY_FONT = Font(name="Arial", size=10)
NOTE_FONT = Font(name="Arial", size=9, italic=True)
WRAP = Alignment(wrap_text=True, vertical="top")


def new_sheet(name):
    return wb.create_sheet(name)


def write_title(ws, title, subtitle):
    ws["A1"] = title
    ws["A1"].font = TITLE_FONT
    ws["A2"] = subtitle
    ws["A2"].font = NOTE_FONT
    ws["A2"].alignment = WRAP


def write_table(ws, start_row, headers, rows, widths=None):
    for j, h in enumerate(headers, start=1):
        c = ws.cell(row=start_row, column=j, value=h)
        c.font = HEADER_FONT
        c.fill = HEADER_FILL
    for i, r in enumerate(rows, start=start_row + 1):
        for j, v in enumerate(r, start=1):
            c = ws.cell(row=i, column=j, value=v)
            c.font = BODY_FONT
            c.alignment = WRAP
    if widths:
        for j, w in enumerate(widths, start=1):
            ws.column_dimensions[get_column_letter(j)].width = w
    return start_row + 1 + len(rows)


# ---------------------------------------------------------------------
# 72 C-004D Operator Registry
# ---------------------------------------------------------------------
ws = new_sheet("72 C-004D Operator Registry")
write_title(ws, "C-004D OPERATOR REGISTRY",
            "Audit of every symbol the corpus uses in a generator role (Section 12), disambiguated.")
write_table(ws, 4,
    ["Symbol as used in corpus", "Corpus occurrence", "Disambiguated meaning", "This run's notation"],
    [
        ("L = D-A", "DER-SPC-002, GEO-001 (CERTIFIED)", "Structural/spectral graph Laplacian, symmetric, L>=0, L1=0", "L"),
        ("H(t)=e^{-tL}, T_t=e^{tL}", "DER-SPC-004, row 2022-2024", "Heat/diffusion semigroup generated by -L; its generator is literally -L", "H(t) = exp(-tL)"),
        ("'The generator is -L for the continuous-time random walk' (row 2024)", "Markov Semigroup entry", "Asserted, but INCONSISTENT with B-005 for irregular graphs -- see 73 sheet", "flagged as GAP-GENERATOR-001"),
        ("L*, L*P (Fokker-Planck)", "row 2013, 2033-2034; BRIDGE B-005 (CERTIFIED); BRIDGE B-006 (CERTIFIED)", "Adjoint/forward generator of a Markov evolution with stationary measure P_ss=d/(2|E|), reversible via detailed balance", "L*_therm"),
        ("D^{-1}L, LD^{-1}", "NOT written explicitly anywhere in the corpus", "Derived this run as the unique reversible-chain generator/adjoint compatible with the graph's own edges and B-005's stated P_ss (Section 5)", "Q = -D^{-1}L (generator); Q* = Q^T = -LD^{-1} (adjoint)"),
        ("Delta_M = lim L_n (continuum Laplace-Beltrami)", "row 2027, BRIDGE B-004 (OPEN)", "A DIFFERENT operator: the continuum limit of the NORMALIZED Laplacian under graph refinement, unrelated to the finite-shell generator question here", "Delta_M (out of scope for C-004D)"),
        ("L_norm = D^{-1/2}LD^{-1/2}", "Not named in corpus; standard graph-theory object, constructed this run from certified L, D", "Symmetric normalized Laplacian, similar to -Q", "L_norm"),
    ], widths=[46, 40, 60, 30])

# ---------------------------------------------------------------------
# 73 C-004D Spectral vs Thermodynamic
# ---------------------------------------------------------------------
ws = new_sheet("73 C-004D Spec vs Thermo")
write_title(ws, "THE TEXTUAL INCONSISTENCY IN THE SOURCE CORPUS", "Quoted verbatim, both sides.")
write_table(ws, 4,
    ["Claim", "Exact source text", "Location"],
    [
        ("A", "'T_t = e^{tL} | Markov Semigroup | Forward-time semigroup. ... The generator is -L for the continuous-time random walk.'",
         "54_SOURCE_TEXT_CORPUS row 2024"),
        ("B", "'BRIDGE B-005: L* -> P_ss: Invariant Measure Existence (CERTIFIED). Statement: For the Fokker-Planck operator L* associated to the graph Laplacian, the stationary measure P_ss exists, is unique for connected G, and equals P_ss(i)=d_i/(2|E|) (degree distribution). Proof: Perron-Frobenius theorem applied to the transition matrix. ... The detailed balance condition gives the explicit form.'",
         "54_SOURCE_TEXT_CORPUS rows 1954-1957, confirmed again row 2137"),
    ], widths=[8, 90, 40])
r = 8
ws.cell(row=r, column=1, value="Resolution (this run, Theorem C-004D.1):").font = Font(bold=True)
r += 1
ws.cell(row=r, column=1,
        value="Claims A and B are mutually consistent ONLY if the graph is regular (all degrees equal), in which case "
              "D=dI is a scalar multiple of the identity and -D^{-1}L=-L/d, the same operator up to a constant time-rescaling. "
              "For irregular graphs, ker(L)=span{1} forces -L's stationary distribution to be UNIFORM, not degree-weighted, "
              "contradicting claim B's own certified P_ss=d/(2|E|) unless the generator is instead D^{-1}L/its adjoint. "
              "Verified for G0-G4 below (sheet 75): G0 is regular (both claims coincide exactly); G1-G4 are irregular "
              "(claims genuinely diverge, confirmed by direct matrix and spectral comparison).")
ws.cell(row=r, column=1).font = BODY_FONT
ws.cell(row=r, column=1).alignment = WRAP
ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=3)
ws.row_dimensions[r].height = 90

# ---------------------------------------------------------------------
# 74 C-004D Stationary Measure
# ---------------------------------------------------------------------
ws = new_sheet("74 C-004D Stationary Measure")
write_title(ws, "STATIONARY MEASURE RECONCILIATION", "Section 9. Computed for G0-G4.")
rows = [(k, v["N"], v["E"], v["regular"],
         v["L_ones_norm_(should_be_0)"], v["negL_times_Puniform_norm_(should_be_0)"],
         v["Qstar_times_d_norm_(should_be_0)"], v["Qstar_times_Pdegree_norm_(should_be_0)"],
         v["P_uniform_minus_Pdegree_L1"], v["P_uniform_minus_Pdegree_L2"], v["P_uniform_equals_Pdegree"])
        for k, v in G.items()]
write_table(ws, 4,
    ["Shell", "N", "E", "Regular?", "||L*1|| (=0 expect)", "||-L*Punif|| (=0 expect)",
     "||Q* * d|| (=0 expect)", "||Q* * Pdeg|| (=0 expect)", "||Punif-Pdeg||_1", "||Punif-Pdeg||_2", "Punif==Pdeg?"],
    rows, widths=[8, 6, 6, 10, 20, 20, 18, 20, 16, 16, 12])

# ---------------------------------------------------------------------
# 75 C-004D Random Walk Generator
# ---------------------------------------------------------------------
ws = new_sheet("75 C-004D Random Walk Gen")
write_title(ws, "RANDOM-WALK GENERATOR DERIVATION",
            "Section 5. Given: graph edges (A_ij in {0,1}), degree matrix D, and the detailed-balance condition "
            "explicitly invoked in BRIDGE B-005's own proof sketch. The unique reversible continuous-time Markov "
            "chain with rates supported exactly on the graph's edges, detail-balanced w.r.t. the CERTIFIED P_ss=d/(2|E|), "
            "and using no parameters beyond A and D, has rate matrix Lambda_ij = A_ij/d_i (i != j). Verification: "
            "pi_i*Lambda_ij = (d_i/2E)(A_ij/d_i) = A_ij/2E = A_ji/2E = pi_j*Lambda_ji (detailed balance holds exactly, "
            "since A is symmetric). This gives generator Lambda = D^{-1}A - I = -D^{-1}(D-A) = -D^{-1}L = Q. "
            "This is the standard 'simple random walk' generator; it is derived here from the source's own detailed-"
            "balance condition, not imported from an external formulation.")
write_table(ws, 8,
    ["Step", "Result"],
    [
        ("1. Reversibility condition (source: B-005 proof, 'detailed balance condition')", "pi_i * Lambda_ij = pi_j * Lambda_ji for all i,j"),
        ("2. Impose pi = P_ss = d/(2|E|) (source: B-005 statement, CERTIFIED)", "(d_i/2E) Lambda_ij = (d_j/2E) Lambda_ji"),
        ("3. Restrict rates to the graph's own edges, simplest law", "Lambda_ij = A_ij / d_i for i != j"),
        ("4. Verify detailed balance holds exactly", "(d_i/2E)(A_ij/d_i) = A_ij/2E = A_ji/2E = (d_j/2E)(A_ji/d_j)  [PASS, A symmetric]"),
        ("5. Assemble generator matrix", "Lambda = D^{-1}A - I = -D^{-1}(D-A) = -D^{-1}L =: Q"),
        ("6. Forward/adjoint operator on probability vectors", "Q* = Q^T = -L D^{-1} =: L*_therm"),
        ("7. Verify Q* d = 0 (equivalently Q* P_degree = 0)", "Confirmed numerically for G0-G4, sheet 74 (residual < 1e-16)"),
    ], widths=[60, 60])

# ---------------------------------------------------------------------
# 76 C-004D Normalized Laplacian
# ---------------------------------------------------------------------
ws = new_sheet("76 C-004D Normalized Laplacian")
write_title(ws, "NORMALIZED LAPLACIAN SIMILARITY", "Section 7.")
write_table(ws, 4,
    ["Claim", "Status"],
    [
        ("L_norm = D^{1/2} (-Q) D^{-1/2}  [similarity transform]", "PROVEN algebraically and VERIFIED numerically for G0-G4 (sheet 77)"),
        ("Consequence: Spec(-Q) = Spec(L_norm)", "VERIFIED numerically for G0-G4 (eigenvalues match to <1e-6)"),
        ("Consequence: Spec(L) != Spec(L_norm) for irregular G_k", "VERIFIED numerically: G0 (regular) spectra match exactly; G1-G4 (irregular) spectra differ"),
    ], widths=[60, 70])

# ---------------------------------------------------------------------
# 77 C-004D Matrix Equality Audit
# ---------------------------------------------------------------------
ws = new_sheet("77 C-004D Matrix Equality")
write_title(ws, "DIRECT MATRIX-EQUALITY AUDIT (not just eigenvalues)", "Section 6.")
rows = [(k, v["regular"], v["frobenius_||Q-(-L)||_F"], v["L_therm_equals_negL_(Frobenius<1e-8)"],
         v["frobenius_||Qstar-(-L)||_F"], v["Qstar_equals_negL_(Frobenius<1e-8)"],
         v["similarity_L_norm_eq_Dsqrt_negQ_Dinvsqrt"], v["eig_negQ_matches_eig_Lnorm"])
        for k, v in G.items()]
write_table(ws, 4,
    ["Shell", "Regular?", "||Q-(-L)||_F", "Q = -L exactly?", "||Q*-(-L)||_F", "Q* = -L exactly?",
     "L_norm=D^(1/2)(-Q)D^(-1/2)?", "Spec(-Q)=Spec(L_norm)?"],
    rows, widths=[8, 10, 16, 16, 16, 16, 26, 22])

# ---------------------------------------------------------------------
# 78 C-004D Spectral Comparison
# ---------------------------------------------------------------------
ws = new_sheet("78 C-004D Spectral Comparison")
write_title(ws, "SPECTRAL RECONCILIATION", "Section 8.")
rows = [(k, v["lambda1_L"], v["lambda1_Lnorm"], v["lambda1_ratio_L_over_Lnorm"],
         v["lambdamax_L"], v["lambdamax_Lnorm"], v["spec_L_equals_spec_Lnorm"])
        for k, v in G.items()]
write_table(ws, 4,
    ["Shell", "lambda1(L)", "lambda1(L_norm)", "ratio L/L_norm", "lambda_max(L)", "lambda_max(L_norm)", "Spec(L)=Spec(L_norm)?"],
    rows, widths=[8, 16, 18, 16, 16, 20, 22])
r = 12
ws.cell(row=r, column=1,
        value="Note: lambda_max(L_norm)=2.0 exactly for every irregular shell G1-G4. This is the standard graph-theory "
              "fact that the normalized-Laplacian spectrum lies in [0,2] with max=2 attained iff the graph is bipartite "
              "-- every ARBS shell is bipartite by construction (Section 1), so this is expected, not a new finding.")
ws.cell(row=r, column=1).font = NOTE_FONT
ws.cell(row=r, column=1).alignment = WRAP
ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=7)
ws.row_dimensions[r].height = 40

# ---------------------------------------------------------------------
# 79 C-004D H-Theorem Compatibility
# ---------------------------------------------------------------------
ws = new_sheet("79 C-004D H-Theorem Compat")
write_title(ws, "H-THEOREM / CONTINUUM CORRESPONDENCE", "Sections 10-11.")
write_table(ws, 4,
    ["Question", "Answer"],
    [
        ("Does the H-theorem (BRIDGE B-006, sigma=-dF/dt>=0) require detailed balance/reversibility?",
         "YES -- the log-sum-inequality proof of dF/dt<=0 requires P(t) to evolve under a generator for which P_ss is the correct stationary measure; using Q*=-LD^{-1} (detailed-balanced w.r.t. P_ss=d/(2|E|) by construction, sheet 75) satisfies this. Using -L would make the H-theorem's own stated P_ss wrong for irregular graphs, breaking the theorem's hypothesis."),
        ("Is Q*=-LD^{-1} the discrete realization of the registered continuum expression L*P=-div(P * grad(log P_ss))?",
         "PARTIALLY -- Q* is derived (sheet 75) as the master-equation generator of the unique detailed-balanced reversible "
         "chain compatible with the graph's edges and the certified P_ss; this is the standard discrete form associated "
         "with reversible master equations in the literature. Literal convergence of this discrete operator to the "
         "specific continuum differential expression under mesh refinement is a discrete-to-continuum limit statement "
         "that is NOT proved here and is not resolved anywhere in the source corpus (BRIDGE B-004, the analogous "
         "heat-kernel-to-geometry bridge, is itself independently registered OPEN)."),
        ("Status of this correspondence", "DISCRETE STATIONARY-MEASURE RECONCILIATION: DERIVED. "
         "EQUALITY WITH THE REGISTERED CONTINUUM L*: OPEN."),
    ], widths=[50, 100])

# ---------------------------------------------------------------------
# 80 C-004D Time-Scale Audit
# ---------------------------------------------------------------------
ws = new_sheet("80 C-004D Time-Scale Audit")
write_title(ws, "TIME-SCALE AUDIT", "Section 13-14. Which operator does each existing quantity actually belong to?")
write_table(ws, 4,
    ["Quantity", "Operator it belongs to", "Status"],
    [
        ("t_H,k (p_A(t_H)=1/2)", "L (spectral) -- ENG-006/007 explicitly use L and 'positive spectrum', consistent with the certified spectral branch", "Unaffected by this run; no change"),
        ("lambda_c,k = 1/t_H,k", "L (spectral)", "Unaffected by this run; no change"),
        ("delta_spec(G_k) = lambda_1(L_k)", "L (spectral) -- source explicitly writes delta_spec=lambda_2 of L", "Unaffected by this run; no change"),
        ("sigma_k = -dF/dt", "L*_therm = -LD^{-1} (thermodynamic) -- REQUIRES the detailed-balanced generator for its own stated P_ss to be correct (sheet 79)", "Confirms C-004C's blocking issue was real: sigma_k belongs to a DIFFERENT operator than delta_spec/lambda_c"),
        ("Pi_0(G_k)=(delta_spec-lambda_c)/sigma", "MIXED -- numerator from L, denominator from L*_therm", "See sheet 81 (Critical Question)"),
    ], widths=[26, 60, 70])

# ---------------------------------------------------------------------
# 81 C-004D Critical Question / Closure
# ---------------------------------------------------------------------
ws = new_sheet("81 C-004D Closure")
write_title(ws, "CRITICAL QUESTION AND FINAL CLOSURE", "Section 14 + 18.")
r = write_table(ws, 4,
    ["Question", "Answer"],
    [
        ("Does Pi_0 mix quantities from two different generators?", "YES -- delta_spec, lambda_c come from L (spectral); sigma comes from L*_therm (thermodynamic)."),
        ("Is this mixed-generator construction (choose one): "
         "A. source-certified, B. proved equivalent, C. dimensionally/structurally admissible but unproved, D. inconsistent, E. OPEN",
         "C. Dimensionally/structurally admissible (sheet 67, C-004C dimensional audit already passed) but NOT proved "
         "equivalent -- no source theorem shows L and L*_therm produce compatible/comparable scales for this specific "
         "ratio. This is a genuine, not-yet-closed gap, distinct from C-004C's sigma non-identifiability."),
    ], widths=[70, 90])
r += 2
ws.cell(row=r, column=1, value="C-004D FINAL STATUS").font = Font(bold=True, size=12)
r += 1
r = write_table(ws, r,
    ["Object", "Status"],
    [
        ("L_spectral = -L", "CERTIFIED (unchanged, source-defined)"),
        ("L_therm = -D^{-1}L = Q", "DERIVED (this run, Section 5, from B-005's own detailed-balance condition)"),
        ("L*_therm = -LD^{-1} = Q*", "DERIVED (this run); VERIFIED: Q* d = 0, so P_ss=d/(2|E|) recovered exactly"),
        ("L_norm = D^{-1/2}LD^{-1/2}", "CONSTRUCTED (standard object); VERIFIED similar to -Q (Spec(-Q)=Spec(L_norm))"),
        ("L_therm = L_spectral (as matrices)?", "FALSIFIED for G1-G4 (irregular); TRUE for G0 (regular) -- Frobenius norm difference computed exactly, sheet 77"),
        ("GENERATOR RECONCILED BY DEGREE NORMALIZATION", "YES -- L_therm=-D^{-1}L (not -L) is the correct thermodynamic generator for irregular ARBS shells"),
        ("Discrete-to-continuum correspondence with registered L*P=-div(P*grad(log P_ss))", "OPEN (sheet 79)"),
        ("Pi_0 mixed-generator construction", "STATUS C: admissible but unproved (this sheet, above)"),
        ("Overall C-004D status", "PARTIALLY CLOSED -- discrete generator reconciliation DERIVED; continuum correspondence remains the one open dependency"),
    ], widths=[46, 90])
r += 2
ws.cell(row=r, column=1, value="C-004C is NOT reopened by this run: no new sigma_k or Pi_0 ranking was computed. Sections 19 of the governing instructions were followed.")
ws.cell(row=r, column=1).font = NOTE_FONT
ws.cell(row=r, column=1).alignment = WRAP
ws.merge_cells(start_row=r, start_column=1, end_row=r, end_column=2)

# ---------------------------------------------------------------------
# 82 C-004D Next Dependency
# ---------------------------------------------------------------------
ws = new_sheet("82 C-004D Next Dependency")
write_title(ws, "EXACTLY ONE NEXT UNRESOLVED UPSTREAM DEPENDENCY", "")
ws["A4"] = ("Prove or disprove that the discrete reversible-chain generator L*_therm = -LD^{-1}, derived this run "
            "from the graph's own edges and the certified detailed-balance/stationary-measure condition (BRIDGE B-005), "
            "is the correct discrete realization of the source's registered continuum expression "
            "L*P = -div(P * grad(log P_ss)) -- i.e. establish (or formally register as a separate open bridge, "
            "analogous to BRIDGE B-004's heat-kernel-to-geometry limit) the discrete-to-continuum correspondence for "
            "the thermodynamic branch specifically. This is required before sigma_k's dynamical definition can be "
            "considered fully pinned to a single, unambiguous operator -- and it is logically prior to attempting any "
            "new choice of P(0)/evaluation time for C-004C, since that choice would otherwise be made relative to an "
            "operator whose continuum meaning is still unverified.")
ws["A4"].font = Font(name="Arial", size=12, bold=True)
ws["A4"].alignment = WRAP
ws.merge_cells("A4:E4")
ws.row_dimensions[4].height = 140

wb.save(OUT)
print("saved", OUT)
print("total sheets:", len(wb.sheetnames))
